services: 

  frontend:
    image: store-frontend:latest
    environment: 
      - ProductEndpoint=http://products-backend:8080
    ports:
      - "32000:8080"
    depends_on: 
      - products-backend
  products-backend:
    image: products-backend:latest
    ports: 
      - "32001:8080"